#!/usr/bin/env bash

GLOBAL=./global-options.txt
LOCAL=./local-options.txt

SAMPLE=./sample-options.txt

GLOBAL=./pglobal-options.txt
LOCAL=./partial-options.txt
SYNCED=./synced-options.txt

# THE IDEA:
#
# global-options.txt : the global file containing default settings
# options.txt        : the local options file for a game instance
# synced-options.txt : the list of synced options and their most recent synced value. the value here is used to determine if the setting was changed
#
# initially: create a file called synced-options.txt. this file contains the list of settings (and their initial values) that will be synced between the settings files.
#            initially this file could either contain: every setting, no settings, only identical settings. every setting is best for new instances, only identical for existing instances.
#
# on game start: read gloal-options.txt, local options.txt, and synced-options.txt. recreate synced-options.txt: if synced[opt] == local[opt]: add to sync, else omit.
#                for every synced option, replace the local option with the global option, and update synced-options.txt.

# TODO: modes? "always change": overwrite everything in synced regardless of if it's changed locally, "respect": respect local changes and don't overwrite them

# TODO: should synced options be remove-only or should it automatically add back options where local==global

# TODO: determine order with tsort? item -> next or prev -> item

changed() {
  comm -i13 <(sort "$1") <(sort "$2")
}

declare -A global_options local_options synced_options _seen_options changed_options
declare -a options_order

load_file() {
  local file="$1"
  local -n map="$2"

  while IFS= read line ; do
    IFS=: read -r key val <<< "$line"
    map["$key"]="$val"

    if [[ ! -v _seen_options["$key"] ]] ; then
      options_order+=("$key")
      _seen_options["$key"]=1
    fi

  done < "$file"
}

printmap() {
  local -n map="$1"

  local -a sorted_keys=("${options_order[@]}" "${!map[@]}")

  sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))

  for key in "${sorted_keys[@]}" ; do
    [[ -v map["$key"] ]] && printf '%s\n%s\n' "$key" "${map["$key"]}"
  done | paste -d' ' - - | column -t
}

savemap() {
  local -n map="$1"

  local -a sorted_keys=("${options_order[@]}" "${!map[@]}" "${!synced_options[@]}")

  sorted_keys=($(IFS=$'\n' ; echo "${sorted_keys[*]}" | command cat -n | sort -uk2 | sort -nk1 | cut -f2-))

  for key in "${options_order[@]}" ; do
    if [[ -v synced_options["$key"] && "${synced_options["$key"]}" == "${local_options["$key"]}" ]] ; then
      local_options["$key"]="${global_options["$key"]}"
    fi

    unset synced_options["$key"]
  done

  # for key in "${synced_options[@]}" ; do
  #   local_options["$key"]="${local_options["$key"]}"
  #   unset synced_options["$key"]
  # done

  # for key in "${!synced_options[@]}" ; do
  #   if [[ "${synced_options["$key"]}" == "${local_options["$key"]}" ]] ; then
  #     local_options["$key"]="${global_options["$key"]}"
  #   fi
  #
  #   unset synced_options["$key"]
  # done
}

# creates the sync file but DOES NOT CHANGE options.txt
initcmd() {
  local mode="$1"
  local global_file="$2"
  local sync_file="${3:-./synced-options.txt}"

  case "${mode,,}" in
    # creates an empty sync file
    "empty")
      ;;

    # creates a sync file with every option in synced-options.txt
    "fullclone" | "full-clone")
      load_file "$global_file" global_options
      for key in "${options_order[@]}" ; do
        synced_options["$key"]=""
      done
      ;;
  esac
}

computesynced() {
  for opt in "${!synced_options[@]}" ; do
    if [[ "${synced_options["$opt"]}" == "${local_options["$opt"]}" ]] ; then
      local_options["$opt"]="${global_options["$opt"]}"
      synced_options["$opt"]="${global_options["$opt"]}"
    else
      unset synced_options["$opt"]
    fi
  done
}

# initcmd "fullclone" "$GLOBAL"
# printmap synced_options

load_file "$GLOBAL" global_options
load_file "$LOCAL" local_options
load_file "$SYNCED" synced_options
# load_file <(changed "$GLOBAL" "$LOCAL") changed_options

# echo "${options_order[@]}"

# printmap synced_options

# echo "before:"
# printmap local_options
#
# echo
# echo
# printmap synced_options
#
# computesynced
#
# echo
# echo "after:"
# printmap local_options
#
# echo
# echo
# printmap synced_options

# load_file "$SAMPLE" 'global_options'

# printmap global_options

printmap local_options
echo
echo

computesynced
printmap synced_options

echo
echo

printmap local_options

# printmap changed_options

# echo "${changed_options}"

# changed "$GLOBAL" "$LOCAL"

# load_file "$LOCAL" local_options
# printmap local_options

# while IFS= read line ; do
#   IFS=: read -r key value <<< $line
#   echo $key $value
# done < $GLOBAL
